# Generated by Django 3.2.16 on 2023-01-19 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_alter_book_appointment_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Appointment',
            new_name='BookAppointment',
        ),
        migrations.AlterModelOptions(
            name='bookappointment',
            options={'ordering': ['created_on']},
        ),
    ]
