# Generated by Django 3.2.16 on 2023-01-21 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookappointment_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
