# Generated by Django 3.2.16 on 2023-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_bookappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
