# Generated by Django 3.2.19 on 2023-06-09 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookappointment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
